#theme: minima
remote_theme: jekyll/minima
title: Ryon Riley
description: A blog about technology, engineering, and general life topics.

header_pages:
  - about.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: G-Y1990BXQYK

minima:
  skin: dark
  
  # Generate social links in footer.
  social_links:
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/ryonriley" }
    - { platform: github,         user_url: "https://github.com/ryonriley" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/3277423/rynoknows" }
    - { platform: slack,          user_url: "https://macadmins.slack.com/team/U011GHLT51T" }
