theme: minima
title: Ryon Riley's Blog
author: Ryon Riley

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/ryonriley

# Analytics
analytics:
  provider               : google-gtag # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : G-Y1990BXQYK
    anonymize_ip         : false # true, false (default)
